// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_islands_Hero from "./islands/Hero.tsx";
import * as $_islands_Skills from "./islands/Skills.tsx";
import * as $_islands_Experience from "./islands/Experience.tsx";
import * as $_islands_Projects from "./islands/Projects.tsx";
import * as $_islands_Contact from "./islands/Contact.tsx";
import * as $_routes__app from "./routes/_app.tsx";
import * as $_routes_index from "./routes/index.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_routes__app,
    "./routes/index.tsx": $_routes_index,
  },
  islands: {
    "./islands/Hero.tsx": $_islands_Hero,
    "./islands/Skills.tsx": $_islands_Skills,
    "./islands/Experience.tsx": $_islands_Experience,
    "./islands/Projects.tsx": $_islands_Projects,
    "./islands/Contact.tsx": $_islands_Contact,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
